/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "bold": boolean;
    }
    interface MyWrapper {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyWrapperElement extends Components.MyWrapper, HTMLStencilElement {
    }
    var HTMLMyWrapperElement: {
        prototype: HTMLMyWrapperElement;
        new (): HTMLMyWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-wrapper": HTMLMyWrapperElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "bold"?: boolean;
    }
    interface MyWrapper {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-wrapper": MyWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-wrapper": LocalJSX.MyWrapper & JSXBase.HTMLAttributes<HTMLMyWrapperElement>;
        }
    }
}
